package uabc.ic.benjaminbolanos.practica4;

/**
 * Clase para modelar la parte de mostrar todos los estados de México.
 * @author benjabolanos
 */
public class Estados extends javax.swing.JPanel {
    private EstadosControl control;

    /**
     * Constructor que inicializa los componentes graficos, el control
     * y avanza la lista hacia la primera posición.
     */
    public Estados() {
        initComponents();
        control = new EstadosControl();
        avanzar();
    }
    
    /**
     * Método para avanzar hacia el siguiente estado. Si es el final de la lista,
     * muesta un label que lo indica. Cambia la información hacia el estado actual.
     */
    private void avanzar(){
        avisoLabel.setVisible(control.avanzarLista());
        Estado actual = control.getEstadoActual();
        setEstado(actual);
    }
    
    /**
     * Método para cambiar la información de los componentes graficos, con la
     * información del Estado que recibe.
     * @param estado Estado que se mostrará visualmente.
     */
    public void setEstado(Estado estado){
        nombreLabel.setText(estado.getNombre());
        escudoIcon.setIcon(estado.getEscudo());
        escudoIcon.setToolTipText(
            "<html>" +
            "Escudo del Estado: " + estado.getNombre() + "<br>" +
            "Capital: " + estado.getCapital() + "<br>" +
            "Año de Fundación: " + estado.getAñoFundacion() + "<br>" +
            "Extensión Territorial: " + estado.getExtensionTerritorial()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mezclarButton = new javax.swing.JButton();
        escudoIcon = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        avisoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mezclarButton.setBackground(new java.awt.Color(204, 255, 255));
        mezclarButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        mezclarButton.setForeground(new java.awt.Color(51, 51, 51));
        mezclarButton.setText("Mezclar Lista");
        mezclarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mezclarButtonActionPerformed(evt);
            }
        });
        add(mezclarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 50));

        escudoIcon.setText("EscudoHolder");
        escudoIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        escudoIcon.setMaximumSize(new java.awt.Dimension(512, 512));
        escudoIcon.setMinimumSize(new java.awt.Dimension(512, 512));
        escudoIcon.setPreferredSize(new java.awt.Dimension(512, 512));
        escudoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escudoIconMouseClicked(evt);
            }
        });
        add(escudoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLabel.setText("Nombre del Estado");
        add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1920, 80));

        avisoLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        avisoLabel.setForeground(new java.awt.Color(255, 51, 51));
        avisoLabel.setText("FIN DE LA LISTA");
        add(avisoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento al dar click en el icono del escudo. Se avanza al siguiente
     * estado.
     * @param evt 
     */
    private void escudoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escudoIconMouseClicked
        avanzar();
    }//GEN-LAST:event_escudoIconMouseClicked

    /**
     * Evento al dar click en el boton de Mezclar. Mezcla la lista de estados
     * y avanza al siguiente estado (en este caso el primero del nuevo orden)
     * @param evt 
     */
    private void mezclarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mezclarButtonActionPerformed
        control.mezclar();
        avanzar();
    }//GEN-LAST:event_mezclarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JLabel escudoIcon;
    private javax.swing.JButton mezclarButton;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
