package uabc.ic.benjaminbolanos.practica4;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 * Clase que modela un juego lúdico de adivinar el escudo de un estado. En esta clase
 * se reunen el control lógico y gráfico del juego.
 * @author benjabolanos
 */
public class JuegoView extends javax.swing.JPanel {
    private JuegoControl control;
    private boolean intentoRealizado;
    
    
    /**
     * Creates new form AdivinaEscudo
     */
    public JuegoView() {
        initComponents();
        control = new JuegoControl();
        nuevaRonda();
    }
    
    /**
     * Método que crea un nuego juego y pone los escudos posibles y reinicia las
     * demas variables.
     */
    private void nuevaRonda(){
        control.crearJuego();
        Estado[] estados = control.getOpciones();
        escudo1Label.setIcon(estados[0].getEscudo());
        escudo2Label.setIcon(estados[1].getEscudo());
        escudo3Label.setIcon(estados[2].getEscudo());
        nombreEstadoLabel.setText(estados[control.getRespuesta()].getNombre());
        escudo1Label.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        escudo2Label.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        escudo3Label.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        intentoRealizado = false;
    }
    
    private void realizarIntento(JLabel label, int respuesta){
        if(!intentoRealizado){
            if(control.checarRespuesta(respuesta)){
                label.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
                control.aumentarPuntaje();
                label.setText("Puntaje: "+control.getPuntaje());
            } else {
                label.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            }
            intentoRealizado = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        escudo3Label = new javax.swing.JLabel();
        escudo2Label = new javax.swing.JLabel();
        escudo1Label = new javax.swing.JLabel();
        nombreEstadoLabel = new javax.swing.JLabel();
        nuevaRondaButton = new javax.swing.JButton();
        puntajeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(51, 51, 51));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("ADIVINA EL ESTADO");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 6, 1970, -1));

        escudo3Label.setText("escudo3Holder");
        escudo3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        escudo3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escudo3LabelMouseClicked(evt);
            }
        });
        add(escudo3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 80, 512, 512));

        escudo2Label.setText("escudo2Holder");
        escudo2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        escudo2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escudo2LabelMouseClicked(evt);
            }
        });
        add(escudo2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 512, 512));

        escudo1Label.setBackground(new java.awt.Color(204, 204, 0));
        escudo1Label.setText("escudo1Holder");
        escudo1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        escudo1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escudo1LabelMouseClicked(evt);
            }
        });
        add(escudo1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 512, 512));

        nombreEstadoLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        nombreEstadoLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreEstadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEstadoLabel.setText("Nombre del Estado");
        add(nombreEstadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 524, -1));

        nuevaRondaButton.setBackground(new java.awt.Color(204, 255, 204));
        nuevaRondaButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        nuevaRondaButton.setForeground(new java.awt.Color(51, 51, 51));
        nuevaRondaButton.setText("Nueva Ronda");
        nuevaRondaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaRondaButtonActionPerformed(evt);
            }
        });
        add(nuevaRondaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, -1, 50));

        puntajeLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        puntajeLabel.setForeground(new java.awt.Color(51, 51, 51));
        puntajeLabel.setText("Puntaje: 0");
        add(puntajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void escudo1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escudo1LabelMouseClicked
        realizarIntento(escudo1Label,0);
    }//GEN-LAST:event_escudo1LabelMouseClicked

    private void escudo2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escudo2LabelMouseClicked
        realizarIntento(escudo2Label,1);
    }//GEN-LAST:event_escudo2LabelMouseClicked

    private void escudo3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escudo3LabelMouseClicked
        realizarIntento(escudo3Label,2);
    }//GEN-LAST:event_escudo3LabelMouseClicked

    private void nuevaRondaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaRondaButtonActionPerformed
        nuevaRonda();
    }//GEN-LAST:event_nuevaRondaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel escudo1Label;
    private javax.swing.JLabel escudo2Label;
    private javax.swing.JLabel escudo3Label;
    private javax.swing.JLabel nombreEstadoLabel;
    private javax.swing.JButton nuevaRondaButton;
    private javax.swing.JLabel puntajeLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
